# Generated by Django 2.2.6 on 2019-10-14 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('slug', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('screen_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('gameInstanceId', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('game', models.ForeignKey(default='situations', on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('participants', models.ManyToManyField(to='games.User')),
            ],
        ),
    ]
