# Generated by Django 2.2.6 on 2019-10-14 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('gameInstance', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='games.GameInstance')),
                ('player', models.ForeignKey(default='situations', on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='FeelinLuckySubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=30)),
                ('filename', models.CharField(max_length=50)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='games.User')),
                ('gameInstance', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='games.GameInstance')),
            ],
        ),
        migrations.CreateModel(
            name='FeelinLuckyGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=30)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='authorship_guess', to='games.User')),
                ('guesser', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='games.User')),
                ('submission', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='games.FeelinLuckySubmission')),
            ],
        ),
    ]
