# Generated by Django 2.2.6 on 2019-10-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gameinstance_accepting_joins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
