# Generated by Django 2.2.6 on 2019-10-15 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20191015_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='game',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='score',
            name='player',
            field=models.ForeignKey(default='situations', on_delete=django.db.models.deletion.CASCADE, to='games.User'),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
