# Generated by Django 2.2.6 on 2019-10-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20191015_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='feelinluckysubmission',
            name='candidates',
            field=models.CharField(default='', max_length=200),
        ),
    ]
